package world

var map168SourceNPCs = []sourceNPCEntry{
	{
		Handle:      "4720542615647172",
		DisplayName: "白源镇告示栏",
		SourceQuery: "npc/公告牌.swf",
		SpriteName:  "gonggaopai",
		Width:       136,
		Height:      149,
		SpawnFlash:  SpawnPoint{X: 724, Y: 430},
		QuestState:  0,
	},
	{
		Handle:      "4710542615621525",
		DisplayName: "向隐",
		SourceQuery: "npc/向隐.swf",
		SpriteName:  "xiangyin",
		Width:       69,
		Height:      151,
		SpawnFlash:  SpawnPoint{X: 1170, Y: 434},
		QuestState:  2,
		GuildName:   "\u533b\u7597\u5e08",
		GuildPic:    "5002",
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message:   "我是广青军医护向隐，白源镇遭此大劫，实在让人看不下去。作为救死扶伤的郎中，我只能眼睁睁地看着他们离去而无能为力，实在太难受了......",
			Answers: []AnswerOption{
				{Handle: "5q3gs", Msg: "<m/>消灭小恶鬼"},
				{Handle: "5q4os", Msg: "<ml><m/>镇长让我来帮你。"},
				{Handle: "5q5gs", Msg: "<ml><m/>三七伤药"},
				{Handle: "5q7gs", Msg: "<ml><m/>帮助苦虚无"},
				{Handle: "5q54gs", Msg: "<m/>送药"},
				{Handle: "5q57gs", Msg: "<ml><m/>治疗心病"},
				{Handle: "5q58gs", Msg: "<ml><m/>治疗心病"},
				{Handle: "5q43gs", Msg: "<m/>埋伏之战"},
				{Handle: "aq28gs", Msg: "<m/>花泪解药"},
				{Handle: "aq29gs", Msg: "<m/>根治之法"},
				{Handle: "aq31os", Msg: "<m/>药到病除"},
				{Handle: "2", Msg: "进行治疗"},
				{Handle: "1", Msg: "查看商店"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
	{
		Handle:      "4730542615655127",
		DisplayName: "通天八卦炉<ma>",
		SourceQuery: "npc/通天八卦炉.swf",
		SpriteName:  "bagualu",
		Width:       264,
		Height:      244,
		SpawnFlash:  SpawnPoint{X: 1759, Y: 440},
		QuestState:  0,
		GuildName:   "\u5408\u6210\u9053\u5177",
		GuildPic:    "5001",
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message:   "八卦炉内燃烧着熊熊烈火......\n((如果拥有造物魔晶或特殊布料的话，便可以放入炉内进行冶炼合成稀有的道具。这些材料可以通过打开吉祥袋、如意袋或乾坤袋获得。注：在【商城】内可以买入【吉祥袋】。))",
			Answers: []AnswerOption{
				{Handle: "1", Msg: "合成稀有道具"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
}

var map169SourceNPCs = []sourceNPCEntry{
	{
		Handle:      "5040542617131880",
		DisplayName: "袁天纲",
		SourceQuery: "npc/袁天纲.swf",
		SpriteName:  "yuantiangang",
		Width:       75,
		Height:      164,
		SpawnFlash:  SpawnPoint{X: 805, Y: 400},
		QuestState:  2,
		GuildName:   "\u6280\u80fd\u5bfc\u5e08",
		GuildPic:    "5003",
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message:   "((云境沙尘遮碧天，飞将遥指擎天山。沙场点兵辕门外，不胜魔军终不还。))\n我乃广青军总长袁天纲是也，此次听闻魔军重现世间袭击白源，特连夜率领数千名广青士兵前来支援，不曾想还是来晚了一步。",
			Answers: []AnswerOption{
				{Handle: "5q16gs", Msg: "<ml><m/>驱赶毒蜂的妙方"},
				{Handle: "5q21ns", Msg: "<mn/>玄龟之甲【进行中】"},
				{Handle: "5q25gs", Msg: "<m/>魔王降世"},
				{Handle: "5q31gs", Msg: "<ml><m/>消灭源头"},
				{Handle: "5q47gs", Msg: "<m/>水晶项链"},
				{Handle: "5q50gs", Msg: "<m/>千里送礼"},
				{Handle: "5q53gs", Msg: "<m/>怪异之举"},
				{Handle: "5q59gs", Msg: "<m/>古铸之法"},
				{Handle: "1", Msg: "学习技能"},
				{Handle: "0", Msg: "<c/>关闭"},
			},
		},
	},
	{
		Handle:      "5060542617335713",
		DisplayName: "妖术狐狸",
		SourceQuery: "npc/狐狸.swf",
		SpriteName:  "huli",
		Width:       58,
		Height:      111,
		SpawnFlash:  SpawnPoint{X: 1238, Y: 450},
		QuestState:  0,
		GuildName:   "\u4f20\u9001\u5927\u5e08",
		GuildPic:    "5005",
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message:   "这((白源镇))镇已被魔军洗劫，早已成一堆废墟，本座在此的生意略显惨淡，少侠想去哪里？~",
			Answers: []AnswerOption{
				{Handle: "3", Msg: "传送到【广青镇】(铜钱x500)"},
				{Handle: "4", Msg: "传送到【乌梁营地】(未激活！)"},
				{Handle: "5", Msg: "传送到【葬龙潭】(铜钱x500)"},
				{Handle: "help", Msg: "未激活是什么意思？"},
				{Handle: "0", Msg: "<c/>关闭（VIP可获每日免费传送次数）"},
			},
		},
	},
	{
		Handle:      "5050542617322114",
		DisplayName: "白叟",
		SourceQuery: "npc/白叟.swf",
		SpriteName:  "baisou",
		Width:       45,
		Height:      148,
		SpawnFlash:  SpawnPoint{X: 1618, Y: 468},
		QuestState:  2,
		GuildName:   "\u4ed3\u5e93\u7ba1\u7406",
		GuildPic:    "5004",
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message:   "老朽乃白源镇长白叟，老朽眼睁睁地看着整个白源镇一夕之间成为一片废墟，实在悲愤交集。谁会想到魔军会突然袭来？！！我无论如何也要熬到魔军被消灭的那一天...",
			Answers: []AnswerOption{
				{Handle: "5q10os", Msg: "<ml><m/>白镇长，需要帮忙的吗。"},
				{Handle: "5q11gs", Msg: "<ml><m/>沼泽采石"},
				{Handle: "5q54os", Msg: "<m/>这是向隐让我送来的药。"},
				{Handle: "5q55gs", Msg: "<m/>最后一份药"},
				{Handle: "5q60ns", Msg: "<mn/>奇怪的考验【进行中】"},
				{Handle: "6", Msg: "使用仓库"},
				{Handle: "1", Msg: "住店绑定"},
				{Handle: "2", Msg: "收发信件"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
	{
		Handle:      "5070542617350720",
		DisplayName: "排行告示",
		SourceQuery: "npc/公告牌.swf",
		SpriteName:  "gonggaopai",
		Width:       136,
		Height:      149,
		SpawnFlash:  SpawnPoint{X: 2208, Y: 430},
		QuestState:  0,
	},
}

var map170SourceNPCs = []sourceNPCEntry{
	{
		Handle:      "5310542617702520",
		DisplayName: "游氏子",
		SourceQuery: "npc/游氏子.swf",
		SpriteName:  "youshizi",
		Width:       149,
		Height:      172,
		SpawnFlash:  SpawnPoint{X: 745, Y: 423},
		QuestState:  2,
		GuildName:   "\u9053\u5177\u5546",
		GuildPic:    "5001",
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message:   "前几日这白源镇遭魔军围攻了。那天我出镇采购货物，等我回来才发现自己竟然逃过了一场大劫，亏我福大命大。",
			Answers: []AnswerOption{
				{Handle: "5q6gs", Msg: "<m/>消灭瘴气泥巴"},
				{Handle: "5q44gs", Msg: "<m/>千里送信"},
				{Handle: "5q46ns", Msg: "<mn/>王花花蕾【进行中】"},
				{Handle: "1", Msg: "道具商店"},
				{Handle: "3", Msg: "原石合成"},
				{Handle: "2", Msg: "查看交易行"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
	{
		Handle:      "5300542617580783",
		DisplayName: "苦虚无",
		SourceQuery: "npc/苦虚无.swf",
		SpriteName:  "kuxuwu",
		Width:       88,
		Height:      145,
		SpawnFlash:  SpawnPoint{X: 1173, Y: 430},
		QuestState:  4,
		GuildName:   "\u953b\u9020\u5e08",
		GuildPic:    "5000",
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message:   "想我苦虚无，空有一身本领，却没从魔军的手中救得辛苦养育自己多年的老父亲。 我苦虚无誓与魔军不共戴天，此生若不能为父报仇，誓不为人！",
			Answers: []AnswerOption{
				{Handle: "5q7os", Msg: "<ml><m/>有什么需要帮忙的吗。"},
				{Handle: "5q8gs", Msg: "<ml><m/>铁矿之需"},
				{Handle: "5q10gs", Msg: "<ml><m/>房屋搭建"},
				{Handle: "5q12gs", Msg: "<m/>恐怖的王花"},
				{Handle: "5q22gs", Msg: "<m/>蜂胶解药"},
				{Handle: "5q48gs", Msg: "<m/>缺少原料"},
				{Handle: "5q49gs", Msg: "<m/>项链做成"},
				{Handle: "5q55os", Msg: "<m/>向隐姐让我送来的药。"},
				{Handle: "5q56gs", Msg: "<m/>治疗心病"},
				{Handle: "2", Msg: "购买武器"},
				{Handle: "3", Msg: "购买护具"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
}

var map169SourceNPCDialogueReplies = map[sourceNPCDialogueReplyKey]sourceNPCDialogueEntry{
	{
		Handle:       "5040542617131880",
		MsgHandle:    "1",
		AnswerHandle: "1",
	}: {
		MsgHandle: "10",
		Message:   "你想学习什么职业的技能？",
		Answers: []AnswerOption{
			{Handle: "7", Msg: "战士技能"},
			{Handle: "8", Msg: "术士技能"},
			{Handle: "9", Msg: "游侠技能"},
			{Handle: "0", Msg: "<c/>下次再说"},
		},
	},
}
