package world

var map1SourceNPCs = []sourceNPCEntry{
	{
		Handle:      "1000542608713897",
		DisplayName: "一心长态",
		SourceQuery: "npc/一心长态.swf",
		SpriteName:  "yixinchangtai",
		Width:       81,
		Height:      117,
		SpawnFlash:  SpawnPoint{X: 320, Y: 534},
		QuestState:  2,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message: `((一间茅屋从来住，心无是非万境闲。长问尘世谁有路，态意从容若神仙。))
贫道一心长态是也，久居云隐村这风轻云淡之隅，昼来农田耕种，夜来把酒赏月，想来这神仙的生活也不过老夫这般了。
((每日13:00-15:00或者19:00-21:00到我这可以接取生死劫任务))。`,
			Answers: []AnswerOption{
				{Handle: "1q32gs", Msg: "<m/>飞仙洞弑炼"},
				{Handle: "2", Msg: "研习职业"},
				{Handle: "1", Msg: "学习技能"},
				{Handle: "show", Msg: "技能演示"},
				{Handle: "3", Msg: "创建公会"},
				{Handle: "x", Msg: "<c/>关闭"},
			},
		},
	},
	{
		Handle:      "9000542609558425",
		DisplayName: "通天八卦炉<ma>",
		SourceQuery: "npc/通天八卦炉.swf",
		SpriteName:  "bagualu",
		Width:       174,
		Height:      220,
		SpawnFlash:  SpawnPoint{X: 625, Y: 440},
		QuestState:  0,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message: `八卦炉内燃烧着熊熊烈火......
((如果拥有造物魔晶或特殊布料的话，便可以放入炉内进行冶炼合成稀有的道具。这些材料可以通过打开吉祥袋、如意袋或乾坤袋获得。
注：在【商城】内可以购入【吉祥袋】。))`,
			Answers: []AnswerOption{
				{Handle: "1", Msg: "合成稀有道具"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
	{
		Handle:      "2000542608832485",
		DisplayName: "蒙达英",
		SourceQuery: "npc/蒙达英[兄].swf",
		SpriteName:  "mengdaying",
		Width:       57,
		Height:      134,
		SpawnFlash:  SpawnPoint{X: 848, Y: 430},
		QuestState:  3,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message: `((渺渺云陆春复秋，青山碧水空自流。谁怜我辈英雄志，披肝沥胆万古愁！))
为了照顾弟弟，我放弃了小时候要进入天宫做一番大事的心愿，转而拜姬前辈学打铁。不知道弟弟这火爆的脾气，什么时候能改改呢？`,
			Answers: []AnswerOption{
				{Handle: "1q28gs", Msg: "<m/>防御工事"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
	{
		Handle:      "3000542609015823",
		DisplayName: "蒙达悟",
		SourceQuery: "npc/蒙达悟[弟].swf",
		SpriteName:  "mengdawu",
		Width:       57,
		Height:      127,
		SpawnFlash:  SpawnPoint{X: 1092, Y: 410},
		QuestState:  2,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message: `师父总说：((天外有天，人外有人))，但他心里一直自以为是天下第一铸剑高手。
一心长态村长却说：((云水后浪推前浪，一代新人胜旧人))，我一定要铸一把天下第一剑给大家看看......`,
			Answers: []AnswerOption{
				{Handle: "1q19gs", Msg: "<m/>准备柴火"},
				{Handle: "1", Msg: "购买武器"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
	{
		Handle:      "4000542609162635",
		DisplayName: "布衣娘",
		SourceQuery: "npc/布衣娘.swf",
		SpriteName:  "buyiniang",
		Width:       55,
		Height:      128,
		SpawnFlash:  SpawnPoint{X: 1408, Y: 432},
		QuestState:  0,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message: `((风吹竹叶飒飒响，眉娘堂前织布忙。衣衫冷暖惟自知，只愿天下无寒霜。))
好想出门见识一下外面的世界啊！若不是身边有爹爹需要供养，我早就像那些男人一样地去闯荡天下了。`,
			Answers: []AnswerOption{
				{Handle: "3q3gs", Msg: "<ml><m/>布衣娘的礼物"},
				{Handle: "1", Msg: "购买护具"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
	{
		Handle:      "1100542609593728",
		DisplayName: "交易行管理员",
		SourceQuery: "npc/交易行管理员.swf",
		SpriteName:  "jiaoyihang",
		Width:       46,
		Height:      106,
		SpawnFlash:  SpawnPoint{X: 1759, Y: 450},
		QuestState:  0,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message: `客官来啦？我们((交易行可以为你寄售物品))，有什么宝物需要寄售的吗？
另外你((也可以看看我们这有没有你想要的宝贝))，淘几件回去也不错呀。`,
			Answers: []AnswerOption{
				{Handle: "1", Msg: "查看交易行"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
	{
		Handle:      "5000542609232627",
		DisplayName: "卢掌柜",
		SourceQuery: "npc/卢掌柜.swf",
		SpriteName:  "luzhanggui",
		Width:       71,
		Height:      120,
		SpawnFlash:  SpawnPoint{X: 1916, Y: 450},
		QuestState:  2,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message: `((桂花饼，香气浓，糯米赛玉，红豆如珠。))
欢迎光临云隐客栈，我是卢掌柜。本客栈马上要推出祖传的桂花糯米糕，别忘记了到时候来尝尝。`,
			Answers: []AnswerOption{
				{Handle: "1q22gs", Msg: "<m/>消灭刺鸟"},
				{Handle: "6", Msg: "使用仓库"},
				{Handle: "1", Msg: "住店绑定"},
				{Handle: "2", Msg: "收发信件"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
	{
		Handle:      "6000542609425103",
		DisplayName: "南风先生",
		SourceQuery: "npc/南风先生.swf",
		SpriteName:  "nanfeng",
		Width:       48,
		Height:      107,
		SpawnFlash:  SpawnPoint{X: 2228, Y: 423},
		QuestState:  2,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message: `((一生长命又何求，半生颠沛半生酒。我欲乘风向云去，奈何业已入白首。))
我南风先生颠沛半生，天为被，地为床，酒为食，药为生，不知遇到多少人与事，都如过眼烟云，只觉人生如梦。((这位侠客，15级以前我可以为你免费治疗。))`,
			Answers: []AnswerOption{
				{Handle: "1q21gs", Msg: "<m/>采集草药"},
				{Handle: "2", Msg: "进行治疗"},
				{Handle: "1", Msg: "查看商店"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
	{
		Handle:      "1200542609639689",
		DisplayName: "妖术狐狸",
		SourceQuery: "npc/狐狸.swf",
		SpriteName:  "huli",
		Width:       48,
		Height:      48,
		SpawnFlash:  SpawnPoint{X: 2517, Y: 451},
		QuestState:  0,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message:   `知道((广青镇))吗？它可是方圆百里最繁华的集市哦~`,
			Answers: []AnswerOption{
				{Handle: "2", Msg: "激活本地传送点"},
				{Handle: "3", Msg: "传送到【广青镇】(未激活！)"},
				{Handle: "4", Msg: "传送到【飞仙崖】(未激活！)"},
				{Handle: "help", Msg: "未激活是什么意思？"},
				{Handle: "0", Msg: "<c/>关闭（VIP可获每日免费传送次数）"},
			},
		},
	},
	{
		Handle:      "7000542609490978",
		DisplayName: "丑七品",
		SourceQuery: "npc/七品.swf",
		SpriteName:  "qipin",
		Width:       81,
		Height:      124,
		SpawnFlash:  SpawnPoint{X: 2773, Y: 432},
		QuestState:  2,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message: `((丑字当头照，利字心头绕。娇娘梦里抱，梦醒数元宝。))
我们丑氏家族世世代代在云之大陆的各个村镇经商。客官，来看看我这里有没有你需要的东西。`,
			Answers: []AnswerOption{
				{Handle: "1q23gs", Msg: "<m/>丑七品的梦"},
				{Handle: "1", Msg: "道具商店"},
				{Handle: "3", Msg: "原石合成"},
				{Handle: "2", Msg: "查看交易行"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
	{
		Handle:      "1000542609582165",
		DisplayName: "排行告示",
		SourceQuery: "npc/公告牌.swf",
		SpriteName:  "gonggaopai",
		Width:       136,
		Height:      149,
		SpawnFlash:  SpawnPoint{X: 3000, Y: 400},
		QuestState:  0,
		Dialogue: &sourceNPCDialogueEntry{
			Message: "这里张贴着村里的公告。",
			Answers: []AnswerOption{
				{Handle: "view", Msg: "查看公告"},
				{Handle: "leave", Msg: "离开"},
			},
		},
	},
	{
		Handle:      "8000542609527450",
		DisplayName: "VIP大使",
		SourceQuery: "npc/other/节日大使.swf",
		SpriteName:  "jieridashi",
		Width:       117,
		Height:      151,
		SpawnFlash:  SpawnPoint{X: 2421, Y: 468},
		QuestState:  0,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message: `到商城购买VIP卡，享受VIP尊贵特权，您还在等什么？心动不如行动！
((当前已经是VIP的，VIP时间不可叠加，更换其他VIP的时候会直接覆盖。VIP提升的经验倍率可以和其他双倍经验卡叠加使用。VIP高级新手套装每个角色只能领取一次！))`,
			Answers: []AnswerOption{
				{Handle: "2", Msg: "领取VIP每日奖品"},
				{Handle: "3", Msg: "领取VIP高级新手套装"},
				{Handle: "4", Msg: "黄牛服务"},
				{Handle: "1", Msg: "充值奖励兑换"},
				{Handle: "0", Msg: "<c/>关闭"},
			},
		},
	},
	{
		Handle:      "transp_4",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 3210, Y: 530},
		QuestState:  0,
		Dialogue: &sourceNPCDialogueEntry{
			Message: "可以瞬间传送至该处。",
			Answers: []AnswerOption{
				{Handle: "goto", Msg: "前往"},
				{Handle: "leave", Msg: "离开"},
			},
		},
	},
}

var map2SourceNPCs = []sourceNPCEntry{
	{
		Handle:      "4180542615109515",
		DisplayName: "交易行管理员",
		SourceQuery: "npc/交易行管理员.swf",
		SpriteName:  "jiaoyihang",
		Width:       46,
		Height:      106,
		SpawnFlash:  SpawnPoint{X: 2162, Y: 465},
		QuestState:  0,
	},
	{
		Handle:      "4190542615111877",
		DisplayName: "通天八卦炉<ma>",
		SourceQuery: "npc/通天八卦炉.swf",
		SpriteName:  "bagualu",
		Width:       174,
		Height:      220,
		SpawnFlash:  SpawnPoint{X: 780, Y: 465},
		QuestState:  0,
	},
	{
		Handle:      "4130542614832797",
		DisplayName: "炎衣娘",
		SourceQuery: "npc/炎衣娘.swf",
		SpriteName:  "yanyiniang",
		Width:       55,
		Height:      128,
		SpawnFlash:  SpawnPoint{X: 1026, Y: 481},
		QuestState:  2,
	},
	{
		Handle:      "4110542614676637",
		DisplayName: "无颜",
		SourceQuery: "npc/无颜.swf",
		SpriteName:  "wuyan",
		Width:       48,
		Height:      107,
		SpawnFlash:  SpawnPoint{X: 1781, Y: 463},
		QuestState:  1,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message: `((凡事知足心长乐，人到无求品自高。))<br>我乃药师无颜，有病治病，无病医心。头疼脑热只是小事。`,
			Answers: []AnswerOption{
				{Handle: "2q21gs", Msg: "<m/>采集草药"},
				{Handle: "4q48os", Msg: "<m/>寻找妙方"},
				{Handle: "4q69gs", Msg: "<m/>奇珍雪莲"},
				{Handle: "2", Msg: "进行治疗"},
				{Handle: "1", Msg: "查看商店"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
	{
		Handle:      "4160542615098838",
		DisplayName: "排行告示",
		SourceQuery: "npc/公告牌.swf",
		SpriteName:  "gonggaopai",
		Width:       136,
		Height:      149,
		SpawnFlash:  SpawnPoint{X: 2670, Y: 285},
		QuestState:  0,
	},
	{
		Handle:      "4090542614314425",
		DisplayName: "丑六品",
		SourceQuery: "npc/六品.swf",
		SpriteName:  "liupin",
		Width:       81,
		Height:      124,
		SpawnFlash:  SpawnPoint{X: 2868, Y: 310},
		QuestState:  2,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message: `本店供应各种日常货物，请随意挑选。唉~最近想起我那七弟来了，我们兄弟为了做生意终日奔波各处...`,
			Answers: []AnswerOption{
				{Handle: "4q72os", Msg: "<m/>丑七品的梦"},
				{Handle: "2q23gs", Msg: "<m/>丑家兄弟"},
				{Handle: "4q73gs", Msg: "<m/>广青镇相聚"},
				{Handle: "1", Msg: "道具商店"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
	{
		Handle:      "4120542614739860",
		DisplayName: "阿达奴",
		SourceQuery: "npc/阿达奴.swf",
		SpriteName:  "adanu",
		Width:       57,
		Height:      135,
		SpawnFlash:  SpawnPoint{X: 1413, Y: 463},
		QuestState:  2,
	},
	{
		Handle:      "4170542615108676",
		DisplayName: "妖术狐狸",
		SourceQuery: "npc/狐狸.swf",
		SpriteName:  "huli",
		Width:       48,
		Height:      48,
		SpawnFlash:  SpawnPoint{X: 2370, Y: 465},
		QuestState:  0,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message:   `知道((广青镇))吗？它可是方圆百里最繁华的集市哦~`,
			Answers: []AnswerOption{
				{Handle: "2", Msg: "激活本地传送点"},
				{Handle: "3", Msg: "传送到【广青镇】(未激活！)"},
				{Handle: "4", Msg: "传送到【黄风寨口】(未激活！)"},
				{Handle: "help", Msg: "未激活是什么意思？"},
				{Handle: "0", Msg: "<c/>关闭（VIP可获每日免费传送次数）"},
			},
		},
	},
	{
		Handle:      "4150542615092700",
		DisplayName: "VIP大使",
		SourceQuery: "npc/other/节日大使.swf",
		SpriteName:  "jieridashi",
		Width:       117,
		Height:      151,
		SpawnFlash:  SpawnPoint{X: 306, Y: 615},
		QuestState:  0,
	},
	{
		Handle:      "4140542615070416",
		DisplayName: "噌痴",
		SourceQuery: "npc/噌痴.swf",
		SpriteName:  "cengchi",
		Width:       81,
		Height:      117,
		SpawnFlash:  SpawnPoint{X: 407, Y: 360},
		QuestState:  2,
	},
	{
		Handle:      "4100542614427315",
		DisplayName: "娴无禄",
		SourceQuery: "npc/娴无录.swf",
		SpriteName:  "xianwulu",
		Width:       57,
		Height:      134,
		SpawnFlash:  SpawnPoint{X: 2450, Y: 400},
		QuestState:  3,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message: `这位小侠，可是要打造两件趁手的兵器？！我可是当年云之大陆有名的铸剑高人之后，哼哼！别怪我没提醒你。`,
			Answers: []AnswerOption{
				{Handle: "2q28gs", Msg: "<m/>兵器打造"},
				{Handle: "0", Msg: "<c/>取消"},
			},
		},
	},
	{
		Handle:      "transp_6",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 3000, Y: 500},
		QuestState:  0,
		Dialogue:    &sourceTransportDialogue,
	},
}

var map3SourceNPCs = []sourceNPCEntry{
	{
		Handle:      "4970542616788530",
		DisplayName: "VIP大使",
		SourceQuery: "npc/other/节日大使.swf",
		SpriteName:  "jieridashi",
		Width:       117,
		Height:      151,
		SpawnFlash:  SpawnPoint{X: 372, Y: 595},
		QuestState:  0,
	},
	{
		Handle:      "4910542615957836",
		DisplayName: "申公烈",
		SourceQuery: "npc/申公烈.swf",
		SpriteName:  "shengonglie",
		Width:       108,
		Height:      116,
		SpawnFlash:  SpawnPoint{X: 675, Y: 545},
		QuestState:  0,
	},
	{
		Handle:      "4920542616052493",
		DisplayName: "火娥娘",
		SourceQuery: "npc/火娥娘.swf",
		SpriteName:  "huoeniang",
		Width:       57,
		Height:      135,
		SpawnFlash:  SpawnPoint{X: 1180, Y: 409},
		QuestState:  0,
	},
	{
		Handle:      "5010542616817526",
		DisplayName: "交易行管理员",
		SourceQuery: "npc/交易行管理员.swf",
		SpriteName:  "jiaoyihang",
		Width:       46,
		Height:      106,
		SpawnFlash:  SpawnPoint{X: 1612, Y: 420},
		QuestState:  0,
	},
	{
		Handle:      "4930542616250587",
		DisplayName: "铃铛",
		SourceQuery: "npc/铃铛.swf",
		SpriteName:  "lingdang",
		Width:       72,
		Height:      135,
		SpawnFlash:  SpawnPoint{X: 1829, Y: 426},
		QuestState:  0,
	},
	{
		Handle:      "4990542616803864",
		DisplayName: "通天八卦炉<ma>",
		SourceQuery: "npc/通天八卦炉.swf",
		SpriteName:  "bagualu",
		Width:       174,
		Height:      220,
		SpawnFlash:  SpawnPoint{X: 2139, Y: 430},
		QuestState:  0,
	},
	{
		Handle:      "5000542616815700",
		DisplayName: "妖术狐狸",
		SourceQuery: "npc/狐狸.swf",
		SpriteName:  "huli",
		Width:       48,
		Height:      48,
		SpawnFlash:  SpawnPoint{X: 2370, Y: 465},
		QuestState:  0,
	},
	{
		Handle:      "4940542616468969",
		DisplayName: "叶眉",
		SourceQuery: "npc/叶眉.swf",
		SpriteName:  "yemei",
		Width:       65,
		Height:      156,
		SpawnFlash:  SpawnPoint{X: 2589, Y: 465},
		QuestState:  0,
	},
	{
		Handle:      "4950542616589339",
		DisplayName: "熊猫竹生",
		SourceQuery: "npc/熊猫竹生.swf",
		SpriteName:  "xiongmaozhusheng",
		Width:       74,
		Height:      90,
		SpawnFlash:  SpawnPoint{X: 2862, Y: 426},
		QuestState:  0,
	},
	{
		Handle:      "4960542616750900",
		DisplayName: "介象",
		SourceQuery: "npc/介象.swf",
		SpriteName:  "jiexiang",
		Width:       84,
		Height:      146,
		SpawnFlash:  SpawnPoint{X: 3051, Y: 442},
		QuestState:  0,
	},
	{
		Handle:      "4980542616799322",
		DisplayName: "排行告示",
		SourceQuery: "npc/公告牌.swf",
		SpriteName:  "gonggaopai",
		Width:       136,
		Height:      149,
		SpawnFlash:  SpawnPoint{X: 3325, Y: 420},
		QuestState:  0,
	},
	{
		Handle:      "transp_10",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 3566, Y: 522},
		QuestState:  0,
		Dialogue: &sourceNPCDialogueEntry{
			MsgHandle: "1",
			Message:   "<font color='#990000'size='14'>出村后可能会涉及到强行PK环节，你确定要出村吗？</font>",
			Answers: []AnswerOption{
				{Handle: "1", Msg: "我要出村"},
				{Handle: "x", Msg: "取消"},
			},
		},
	},
}

var map49SourceNPCs = []sourceNPCEntry{
	{
		Handle:      "transp_50",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 2950, Y: 650},
		QuestState:  0,
		Dialogue:    &sourceTransportDialogue,
	},
	{
		Handle:      "transp_48",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 180, Y: 464},
		QuestState:  0,
		Dialogue:    &sourceTransportDialogue,
	},
}

var map50SourceNPCs = []sourceNPCEntry{
	{
		Handle:      "transp_51",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 2647, Y: 424},
		QuestState:  0,
		Dialogue:    &sourceTransportDialogue,
	},
	{
		Handle:      "transp_55",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 2967, Y: 553},
		QuestState:  0,
		Dialogue:    &sourceTransportDialogue,
	},
	{
		Handle:      "transp_49",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 40, Y: 424},
		QuestState:  0,
		Dialogue:    &sourceTransportDialogue,
	},
}

var map79SourceNPCs = []sourceNPCEntry{
	{
		Handle:      "transp_80",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 60, Y: 524},
		QuestState:  0,
		Dialogue:    &sourceTransportDialogue,
	},
}

var map80SourceNPCs = []sourceNPCEntry{
	{
		Handle:      "transp_81",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 80, Y: 534},
		QuestState:  0,
		Dialogue:    &sourceTransportDialogue,
	},
	{
		Handle:      "transp_79",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 2940, Y: 524},
		QuestState:  0,
		Dialogue:    &sourceTransportDialogue,
	},
}

var map81SourceNPCs = []sourceNPCEntry{
	{
		Handle:      "transp_82",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 75, Y: 464},
		QuestState:  0,
		Dialogue:    &sourceTransportDialogue,
	},
	{
		Handle:      "transp_80",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 2940, Y: 464},
		QuestState:  0,
		Dialogue:    &sourceTransportDialogue,
	},
}

var map82SourceNPCs = []sourceNPCEntry{
	{
		Handle:      "transp_83",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 75, Y: 464},
		QuestState:  0,
		Dialogue:    &sourceTransportDialogue,
	},
	{
		Handle:      "transp_81",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 2940, Y: 464},
		QuestState:  0,
		Dialogue:    &sourceTransportDialogue,
	},
}

var map83SourceNPCs = []sourceNPCEntry{
	{
		Handle:      "transp_0",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 341, Y: 363},
		QuestState:  0,
		Dialogue:    &sourceTransportDialogue,
	},
	{
		Handle:      "transp_82",
		RoleID:      "-3",
		DisplayName: "",
		SourceQuery: "transp/flag2.swf",
		SpriteName:  "flag2",
		Width:       158,
		Height:      258,
		SpawnFlash:  SpawnPoint{X: 2930, Y: 480},
		QuestState:  0,
		Dialogue:    &sourceTransportDialogue,
	},
}

var sourceTransportDialogue = sourceNPCDialogueEntry{
	Message: "可以瞬间传送至该处。",
	Answers: []AnswerOption{
		{Handle: "goto", Msg: "前往"},
		{Handle: "leave", Msg: "离开"},
	},
}

var sourceTransportLinks = []sourceTransportLink{
	{FromMapID: 3, ToMapID: 10, Slot: 1},
	{FromMapID: 4, ToMapID: 1, Slot: 0},
	{FromMapID: 4, ToMapID: 5, Slot: 1},
	{FromMapID: 5, ToMapID: 4, Slot: 0},
	{FromMapID: 5, ToMapID: 9, Slot: 1},
	{FromMapID: 9, ToMapID: 5, Slot: 0},
	{FromMapID: 9, ToMapID: 13, Slot: 1},
	{FromMapID: 13, ToMapID: 9, Slot: 0},
	{FromMapID: 13, ToMapID: 14, Slot: 1},
	{FromMapID: 13, ToMapID: 19, Slot: 2},
	{FromMapID: 14, ToMapID: 13, Slot: 0},
	{FromMapID: 14, ToMapID: 15, Slot: 1},
	{FromMapID: 15, ToMapID: 14, Slot: 0},
	{FromMapID: 15, ToMapID: 16, Slot: 1},
	{FromMapID: 16, ToMapID: 15, Slot: 0},
	{FromMapID: 16, ToMapID: 17, Slot: 1},
	{FromMapID: 17, ToMapID: 16, Slot: 0},
	{FromMapID: 17, ToMapID: 18, Slot: 1},
	{FromMapID: 18, ToMapID: 17, Slot: 0},
	{FromMapID: 19, ToMapID: 13, Slot: 0},
	{FromMapID: 19, ToMapID: 20, Slot: 1},
	{FromMapID: 20, ToMapID: 19, Slot: 0},
	{FromMapID: 20, ToMapID: 21, Slot: 1},
	{FromMapID: 21, ToMapID: 20, Slot: 0},
	{FromMapID: 21, ToMapID: 22, Slot: 1},
	{FromMapID: 21, ToMapID: 25, Slot: 2},
	{FromMapID: 22, ToMapID: 21, Slot: 0},
	{FromMapID: 22, ToMapID: 23, Slot: 1},
	{FromMapID: 23, ToMapID: 22, Slot: 0},
	{FromMapID: 23, ToMapID: 24, Slot: 1},
	{FromMapID: 24, ToMapID: 23, Slot: 0},
	{FromMapID: 24, ToMapID: 27, Slot: 1},
	{FromMapID: 25, ToMapID: 21, Slot: 0},
	{FromMapID: 25, ToMapID: 30, Slot: 1},
	{FromMapID: 26, ToMapID: 30, Slot: 0},
	{FromMapID: 26, ToMapID: 28, Slot: 1},
	{FromMapID: 27, ToMapID: 24, Slot: 0},
	{FromMapID: 27, ToMapID: 29, Slot: 1},
	{FromMapID: 28, ToMapID: 26, Slot: 0},
	{FromMapID: 28, ToMapID: 32, Slot: 1},
	{FromMapID: 29, ToMapID: 27, Slot: 0},
	{FromMapID: 30, ToMapID: 25, Slot: 0},
	{FromMapID: 30, ToMapID: 26, Slot: 1},
	{FromMapID: 32, ToMapID: 28, Slot: 0},
}

var map1SourceNPCDialogueReplies = map[sourceNPCDialogueReplyKey]sourceNPCDialogueEntry{
	{
		Handle:       "1000542608713897",
		MsgHandle:    "1",
		AnswerHandle: "2",
	}: {
		MsgHandle: "2",
		Message:   "现在有三个职业可以选择，请从职业选项中选择你希望的职业......",
		Answers: []AnswerOption{
			{Handle: "4", Msg: "了解【战士】的特点"},
			{Handle: "5", Msg: "了解【术士】的特点"},
			{Handle: "6", Msg: "了解【游侠】的特点"},
			{Handle: "0", Msg: "<c/>返回"},
		},
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "2",
		AnswerHandle: "4",
	}: {
		MsgHandle: "13",
		Message:   "<font color='#990000'><b>战士</b></font>若有较强的气力以及物理攻击和防御。弱点在于遇到法术攻击的时候较为吃力。",
		Answers: []AnswerOption{
			{Handle: "0", Msg: "<c/>返回"},
		},
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "2",
		AnswerHandle: "5",
	}: {
		MsgHandle: "14",
		Message:   "<font color='#990000'><b>术士</b></font>这个职业拥有强大的法术攻击和防御能力，但使用的武器类型范围较窄。",
		Answers: []AnswerOption{
			{Handle: "0", Msg: "<c/>返回"},
		},
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "2",
		AnswerHandle: "6",
	}: {
		MsgHandle: "15",
		Message:   "<font color='#990000'><b>游侠</b></font>具有其他职业无法比拟的高敏捷特性，可研习提高物理攻击的技能。",
		Answers: []AnswerOption{
			{Handle: "0", Msg: "<c/>返回"},
		},
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "13",
		AnswerHandle: "0",
	}: {
		MsgHandle: "1",
		Message:   "",
		Answers:   nil,
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "14",
		AnswerHandle: "0",
	}: {
		MsgHandle: "1",
		Message:   "",
		Answers:   nil,
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "15",
		AnswerHandle: "0",
	}: {
		MsgHandle: "1",
		Message:   "",
		Answers:   nil,
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "2",
		AnswerHandle: "0",
	}: {
		MsgHandle: "1",
		Message:   "",
		Answers:   nil,
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "1",
		AnswerHandle: "1",
	}: {
		MsgHandle: "10",
		Message:   "你想学习什么职业的技能？",
		Answers: []AnswerOption{
			{Handle: "7", Msg: "战士技能"},
			{Handle: "8", Msg: "术士技能"},
			{Handle: "9", Msg: "游侠技能"},
			{Handle: "0", Msg: "<c/>返回"},
		},
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "10",
		AnswerHandle: "0",
	}: {
		MsgHandle: "1",
		Message:   "",
		Answers:   nil,
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "1",
		AnswerHandle: "show",
	}: {
		MsgHandle: "sshow",
		Message:   "请选择一个职业技能进行预览。",
		Answers: []AnswerOption{
			{Handle: "show01", Msg: "[战士]奥义.飘血"},
			{Handle: "show02", Msg: "[术士]白猿之怒"},
			{Handle: "show03", Msg: "[游侠]奥义.修罗幻翼拳"},
			{Handle: "x", Msg: "<c/>关闭"},
		},
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "sshow",
		AnswerHandle: "show01",
	}: {
		MsgHandle: "shows01",
		Message:   "((【战士.剑系】的【奥义.飘血】技能展示。))[img]ect/px.swf[/img]",
		Answers: []AnswerOption{
			{Handle: "0", Msg: "<c/>返回"},
		},
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "sshow",
		AnswerHandle: "show02",
	}: {
		MsgHandle: "shows02",
		Message:   "((【战士.法杖】的【白猿之怒】技能展示。))[img]ect/byzn.swf[/img]",
		Answers: []AnswerOption{
			{Handle: "0", Msg: "<c/>返回"},
		},
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "sshow",
		AnswerHandle: "show03",
	}: {
		MsgHandle: "shows03",
		Message:   "((【游侠.拳系】的【奥义.修罗幻翼拳】技能展示。))[img]ect/xlhy.swf[/img]",
		Answers: []AnswerOption{
			{Handle: "0", Msg: "<c/>返回"},
		},
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "shows01",
		AnswerHandle: "0",
	}: {
		MsgHandle: "1",
		Message:   "",
		Answers:   nil,
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "shows02",
		AnswerHandle: "0",
	}: {
		MsgHandle: "1",
		Message:   "",
		Answers:   nil,
	},
	{
		Handle:       "1000542608713897",
		MsgHandle:    "shows03",
		AnswerHandle: "0",
	}: {
		MsgHandle: "1",
		Message:   "",
		Answers:   nil,
	},
	{
		Handle:       "4000542609162635",
		MsgHandle:    "1",
		AnswerHandle: "3q3gs",
	}: {
		MsgHandle: "3q3d_1",
		Message:   "你来啦？一个人出门在外不容易，之前看你穿的单薄，特意给你做了套布衣裤，另外还有一些花卷，就算我送你的礼物吧。",
		Answers: []AnswerOption{
			{Handle: "3q3a_1_1", Msg: "<m/>谢谢您啦。"},
			{Handle: "3q3a_1_2", Msg: "<c/>关闭"},
		},
	},
	{
		Handle:       "2000542608832485",
		MsgHandle:    "1",
		AnswerHandle: "1q28gs",
	}: {
		MsgHandle: "1q28d_1",
		Message: `我刚刚听广青镇来的人说魔军已经打到白源那边了，我们正在修筑防御工事，魔军若来了也能抵御一阵。现在还需要很多木材，你((去【树海_1】的木材采集点采20根木材))过来吧。((【注：该任务2小时一周期】))

[g]=[i=f_i_银元宝^C156C7&24@材料 消耗品&25@9999&19@双击可兑换为1000铜币&20@游戏中的货币&0;用于流通买卖&27@sitem_jhj&101@39.png&103@0&104@0&105@&107@&108@0]银元宝[/]x1`,
		Answers: []AnswerOption{
			{Handle: "1q28a_1_1", Msg: "<m/>我这就去。"},
			{Handle: "1q28a_1_2", Msg: "<c/>关闭"},
		},
	},
}

var map2SourceNPCDialogueReplies = map[sourceNPCDialogueReplyKey]sourceNPCDialogueEntry{
	{
		Handle:       "4110542614676637",
		MsgHandle:    "1",
		AnswerHandle: "2q21gs",
	}: {
		MsgHandle: "2q21d_1",
		Message:   "人算不如天算，在这个节骨眼村西头的王大爷竟然食物中毒，偏偏那解毒丸又吃完了，在下又没有时间前去采摘，小侠若能帮我采些草药回来，在下感激不尽。",
		Answers: []AnswerOption{
			{Handle: "2q21a_1_1", Msg: "<m/>我这就去。"},
			{Handle: "2q21a_1_2", Msg: "<c/>关闭"},
		},
	},
	{
		Handle:       "4110542614676637",
		MsgHandle:    "1",
		AnswerHandle: "4q48os",
	}: {
		MsgHandle: "4q48d_2",
		Message:   "忘情药的配方？问世间情为何物，直叫人生死相许。若是世间真有忘情药，又何须叫人生死相许。",
		Answers: []AnswerOption{
			{Handle: "4q48a_2_1", Msg: "<m/>受教了。"},
			{Handle: "4q48a_2_2", Msg: "<c/>关闭"},
		},
	},
	{
		Handle:       "4110542614676637",
		MsgHandle:    "1",
		AnswerHandle: "4q69gs",
	}: {
		MsgHandle: "4q69d_1",
		Message:   "嗯，如果真不想受相思之苦的话，我倒是有一法可抵得上忘情之药，不过你得先替我完成一件事。",
		Answers: []AnswerOption{
			{Handle: "4q69a_1_1", Msg: "<m/>请讲。"},
			{Handle: "4q69a_1_2", Msg: "<c/>关闭"},
		},
	},
	{
		Handle:       "4110542614676637",
		MsgHandle:    "4q69d_1",
		AnswerHandle: "4q69a_1_1",
	}: {
		MsgHandle: "4q69d_2",
		Message:   "我前日出游寻得一珍贵的药材，名为((雪莲花))，可路途中((被那黄风二寨主夺走))，小侠若能((去【黄风寨】替我夺回雪莲花))，在下自会尽力相助。",
		Answers: []AnswerOption{
			{Handle: "4q69a_2_1", Msg: "<m/>我这就去。"},
			{Handle: "4q69a_2_2", Msg: "<c/>关闭"},
		},
	},
}
